runtime: custom
env: flex

env_variables:
  JWT_SECRET: "tu_clave_secreta_muy_segura_cambiar_en_produccion"
  DB_HOST: ":/cloudsql/mudanzas-app-474101:us-central1:mudanzas-mysql"
  DB_NAME: "plataforma_mudanzas"
  DB_USER: "jmendoza"

beta_settings:
  cloud_sql_instances: "mudanzas-app-474101:us-central1:mudanzas-mysql"

resources:
  cpu: 1000
  memory_gb: 0.5

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
